### ISSUE TITLE
Autopilot UI components

### ISSUE THREAD

**Issue by muzafarova** [universalbasket/css#19]
**Phase 2
Shared and specific Autopilot styles**
_As the Autopilot developer I want to use the latest, common CSS components and elements and extend them to cover new styles for Autopilot components, so that Autopilot specific styles are available for re-use._

Acceptance criteria:  
- Collaborate with other projects to ensure the smooth transition form v1.0 to v2.0 of the CSS Framework.
- **Assess which components currently defined in the v2.0 framework are common to all uses including Autopilot and use them to style Autopilot components in current and future projects.**
  - variables (colour, spacing, font)
  - buttons, badges, tags
  - form elements (?)
  - helpers (text-colour, block-colour, block-mergers)
  - typography

For future iterations, there are potentially common visual elements, that could be unified cross-project and their styles included to the framework under core or project-specific section.

Some part of UI might change soon, so this list is just a quick inventory of the current UI

# Potentially Common

<details>
<summary>Typography (small and tiny size, dense)</summary>

![image](https://user-images.githubusercontent.com/1133326/52061416-23430f00-2566-11e9-9d0b-21aa491cb1f9.png)
![image](https://user-images.githubusercontent.com/1133326/52061435-30f89480-2566-11e9-9339-a5335bf5bed0.png)
![image](https://user-images.githubusercontent.com/1133326/52061439-348c1b80-2566-11e9-9468-a5b2bffb3915.png)
![image](https://user-images.githubusercontent.com/1133326/52061453-3ce45680-2566-11e9-86df-f817cb40a502.png)
![image](https://user-images.githubusercontent.com/1133326/52061461-4241a100-2566-11e9-92e6-cc53d0de4d7e.png)
![image](https://user-images.githubusercontent.com/1133326/52061692-d14eb900-2566-11e9-9150-e5aac81ef0f6.png)
</details>

<details>
<summary>Timer</summary>

Bigger than small badge, close to small button but not intractable.
![image](https://user-images.githubusercontent.com/1133326/52054158-7c557780-2553-11e9-9eb3-6d47665cb5dc.png) (h 17.5px, font 10px)
![image](https://user-images.githubusercontent.com/1133326/52054258-cfc7c580-2553-11e9-8fd7-f86ee70fcd43.png) (h 17px, font 11px)
</details>

<details>
<summary>Timeline</summary>

**Events (context enter/leave, action enter/leave)**

![image](https://user-images.githubusercontent.com/1133326/52059624-3a7ffd80-2562-11e9-8a91-6723cfaaee5c.png)
![image](https://user-images.githubusercontent.com/1133326/52059691-669b7e80-2562-11e9-803c-253b2e317cfe.png)

**Error event**

![image](https://user-images.githubusercontent.com/1133326/52059824-be39ea00-2562-11e9-8dd2-09854254ef17.png)
![image](https://user-images.githubusercontent.com/1133326/52059054-af523800-2560-11e9-9bbe-68991e6d2a42.png)

**Input/Output events/MIMO logs** 

![image](https://user-images.githubusercontent.com/1133326/52059878-e9bcd480-2562-11e9-90d2-3540e2cde884.png)
![image](https://user-images.githubusercontent.com/1133326/52060897-1d006300-2565-11e9-8e16-4c8ea40cb789.png)

**Audit logs (backoffice only)**
![image](https://user-images.githubusercontent.com/1133326/52060952-37d2d780-2565-11e9-880c-3130f883bca0.png)
</details>

<details>
<summary>Error messages</summary>

![image](https://user-images.githubusercontent.com/1133326/52060749-c72bbb00-2564-11e9-9a59-57e449bcda04.png)
![image](https://user-images.githubusercontent.com/1133326/52059963-2dafd980-2563-11e9-96ff-177107f3df76.png)
![image](https://user-images.githubusercontent.com/1133326/52060728-b8dd9f00-2564-11e9-8c1b-8a1b14bae16c.png)
</details>

<details>
<summary>JSON-viewer </summary>

![image](https://user-images.githubusercontent.com/1133326/52060660-92b7ff00-2564-11e9-888b-0a2e4df35930.png)
![image](https://user-images.githubusercontent.com/1133326/52060614-7b791180-2564-11e9-863c-7003687ca83c.png)
</details>

<details>
<summary>Service bar (heading + [icon] domain name)</summary>

![image](https://user-images.githubusercontent.com/1133326/52060026-45875d80-2563-11e9-9afb-eee78260da2c.png)

![image](https://user-images.githubusercontent.com/1133326/52060110-723b7500-2563-11e9-809b-ee633170a864.png)
</details>

<details>
<summary>Tabs</summary>

![image](https://user-images.githubusercontent.com/1133326/52061319-ed058f80-2565-11e9-99a2-87a0007c3a2c.png)
![image](https://user-images.githubusercontent.com/1133326/52060355-ed9d2680-2563-11e9-8f9d-cc05c0f0dee5.png)
![image](https://user-images.githubusercontent.com/1133326/52060323-d9592980-2563-11e9-81e9-2b558502a887.png)
</details>

<details>
<summary>State indicator</summary>

![image](https://user-images.githubusercontent.com/1133326/52060547-5b495280-2564-11e9-86ec-d52d4fa7a424.png)
![image](https://user-images.githubusercontent.com/1133326/52060512-4240a180-2564-11e9-882c-24a5e1a6084f.png)
</details>

<details>
<summary>Tree view </summary>

![image](https://user-images.githubusercontent.com/1133326/52061171-a57f0380-2565-11e9-8de6-6e1109b7fb42.png)
![image](https://user-images.githubusercontent.com/1133326/52060427-17eee400-2564-11e9-8e8b-9c5ad2fdcc9c.png)
![image](https://user-images.githubusercontent.com/1133326/52054614-0520e300-2555-11e9-9f8a-afe0d4b5f60a.png)
![image](https://user-images.githubusercontent.com/1133326/52054791-824c5800-2555-11e9-973c-4c7d65ab3954.png)
</details>

<details>
<summary>Expandable panels</summary>

![image](https://user-images.githubusercontent.com/1133326/52061039-66e94900-2565-11e9-8c8a-54b94dff3689.png)
![image](https://user-images.githubusercontent.com/1133326/52061132-9009d980-2565-11e9-8e42-320423165515.png)
![image](https://user-images.githubusercontent.com/1133326/52061526-6c935e80-2566-11e9-9d3f-7ff84a62f6e6.png)
![image](https://user-images.githubusercontent.com/1133326/52061565-7cab3e00-2566-11e9-9e2a-254ffe0e4494.png)
![image](https://user-images.githubusercontent.com/1133326/52061592-8f257780-2566-11e9-9e4e-714635ac60e2.png)
</details>

<details>
<summary>Code editor</summary>

![image](https://user-images.githubusercontent.com/1133326/52061757-f6dbc280-2566-11e9-9033-8d20deeaadb8.png)
![image](https://user-images.githubusercontent.com/1133326/52061910-618cfe00-2567-11e9-88c8-03a3cd690e91.png)
</details>

# Specific to Autopilot

<details>
<summary>Player</summary>

![image](https://user-images.githubusercontent.com/1133326/52059914-078a3980-2563-11e9-8b5f-cc6788079c4d.png)
</details>

<details>
<summary>Identifiers (job, execution)</summary>

![image](https://user-images.githubusercontent.com/1133326/52061242-cb0c0d00-2565-11e9-9dac-312852cdeec4.png)
![image](https://user-images.githubusercontent.com/1133326/52061300-e4ad5480-2565-11e9-98e2-00aa2fb979c6.png)
</details>

<details>
<summary>Script elements</summary>

![image](https://user-images.githubusercontent.com/1133326/52061346-027ab980-2566-11e9-97f1-58fccc948ead.png)
![image](https://user-images.githubusercontent.com/1133326/52062047-add83e00-2567-11e9-994d-71218b502bdf.png)
</details>

<details>
<summary>UDF pipes</summary>

![image](https://user-images.githubusercontent.com/1133326/52062086-c2b4d180-2567-11e9-87b2-8486f35b7152.png)

</details>

<details>
<summary>Round badges</summary>

![image](https://user-images.githubusercontent.com/1133326/52061985-897c6180-2567-11e9-93f2-e7491d6176d2.png)
![image](https://user-images.githubusercontent.com/1133326/52062006-96995080-2567-11e9-9ad8-6e33e047c3fd.png)
![image](https://user-images.githubusercontent.com/1133326/52062019-9bf69b00-2567-11e9-8aff-f7a2e846a252.png)

</details>

**Comment by muzafarova** [comment]
@emmasalih I'll let you decide what to do with this issue, as I understand this, we're now attempting to unify any elements from "Potentially Common" section yet.

**Comment by inca** [comment]
More essentials for the list:

- Input with Autocomplete (keyboard-friendly)
- Context menu (incl. arbitrary nesting levels, search, docs and keyboard navigation)
- Dropdown menus (incl. labels with icons and separators, as per [recent UI specs](https://github.com/universalbasket/css/files/2828700/Autopilot.Application.Framework.Workspaces.and.Panels.v2.0.pdf))

Not sure if those are common or Autopilot-specific, but they still need to be implemented somewhere (styling, behaviour, etc). Please note that the components listed here aren't simple, because they need to be friendly to visible space (e.g. dropdown shouldn't popup into scrollable area and trigger the scrollbars of its container) and should respect keyboard navigation. Therefore, implementing them is a sizeable UI+UX work (even if done outside CSS framework, in Autopilot-only manner).

**Comment by muzafarova** [comment]
> Input with Autocomplete (keyboard-friendly)

this one might be reused across many projects, but at the moment it's not implemented anywhere else. Sounds like inbox for next framework iteration as we try to not add new requirements now. As far as I understand, we only concerned with styling here, so component logic (such as keyboard-friendliness) is out of concern (but styling for focus will be provided) Correct me if I'm wrong

> Context menu

this is 100% specific to the AP today. 

> Dropdown menus

aren't this context menus as well? not clear from the wireframe

Btw, it would be nice to catch up later this week and decide how to keep, update and demo AP-specific stuff (via CSS Framework demo page, or should we keep this somewhere else) Have you considered web-components that we could inline into our demo page, but their style and everything) lives somewhere else (some kind of AP-UI library)?

**Comment by muzafarova** [comment]
Closing this one as it's agreed to keep AP specific styles within the Autopilot project
