### ISSUE TITLE
Button semantics

### ISSUE THREAD

**Issue by inca** [universalbasket/css#5]
- [ ] Consider only leaving `btn--primary` and `btn--secondary` semantics for button colors
- [ ] Consider adding `btn--outline` (if we need them)
- ~Consider making default button "frameless", so that it's rendered as "just an icon" (but preserving the button metrics)~ — make different component instead

**Comment by inca** [comment]
This seem to be abandoned. Is there any work planned towards standardizing button semantics? Without a concise set of components we will have more and more ad hoc ones with each iteration. Just to list a few (not counting "special occurrences" like playback panels):

- regular coloured buttons  <img width="221" alt="screen shot 2018-03-26 at 13 17 49" src="https://user-images.githubusercontent.com/118196/37900856-1ca3adde-30f8-11e8-8b73-c3410eb4556f.png">

- different colours <img width="158" alt="screen shot 2018-03-26 at 13 18 20" src="https://user-images.githubusercontent.com/118196/37900976-7e87fec4-30f8-11e8-9388-5dfa67c6fcaa.png">

- "icon buttons", few different colours in use already, sometimes with colour-on-hover <img width="137" alt="screen shot 2018-03-26 at 13 15 33" src="https://user-images.githubusercontent.com/118196/37900746-ca3719a0-30f7-11e8-84cd-7648f67ce6af.png">

- "mode buttons" <img width="121" alt="screen shot 2018-03-26 at 13 19 14" src="https://user-images.githubusercontent.com/118196/37900966-72acca12-30f8-11e8-81c2-4edd030925dc.png">

- "frameless buttons" <img width="203" alt="screen shot 2018-03-26 at 13 19 49" src="https://user-images.githubusercontent.com/118196/37900958-6b52c4ce-30f8-11e8-90ab-fa7a5a1c4248.png">

**Comment by muzafarova** [comment]
nothing planned afaik but we should find time and move forward 

@inca could you please take include "special occurrences" like playback panels as well? 

It's fine that the secondary button is not in specs for UDF as long as it's used in other projects

**Comment by emmasalih** [comment]
Can i close this since Mark R is working on it?

**Comment by muzafarova** [comment]
Let's keep it until we we deliver v2.0.0! (soon)

**Comment by muzafarova** [comment]
The latest solution is 3 kinds of buttons: 
- default (no special styling)
- `button--primary` (primary action within a context, only one per context) - blue background 
- `button--secondary` (secondary action when applicable) - blue outline

Where blue is the primary call to action colour. It can be overridden using variables

For button sets there is an additional class `button--accent` to tint the button that is active (only one per set) - this is when applicable
